# Generated by Django 3.0.4 on 2021-09-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuario', models.CharField(max_length=200, unique=True)),
                ('senha', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=500)),
                ('telefone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuario', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaCompradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=200)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Classe')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('unidadeMedida', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('quantidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdemFornecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icms', models.FloatField()),
                ('ipi', models.FloatField()),
                ('frete', models.CharField(max_length=200)),
                ('dataEntrega', models.DateTimeField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Comprador')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.EmpresaCompradora')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Fornecedor')),
                ('itens', models.ManyToManyField(to='SimpleBuy.Item')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroNota', models.IntegerField(unique=True)),
                ('icms', models.FloatField()),
                ('ipi', models.FloatField()),
                ('empresaDestinada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.EmpresaCompradora')),
                ('empresaEmitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Fornecedor')),
                ('itens', models.ManyToManyField(to='SimpleBuy.Item')),
                ('ofs', models.ManyToManyField(to='SimpleBuy.OrdemFornecimento')),
            ],
        ),
        migrations.AddField(
            model_name='empresacompradora',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Endereco'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.EmpresaCompradora'),
        ),
        migrations.CreateModel(
            name='ClasseFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Classe')),
                ('fornecedorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Estado'),
        ),
    ]
