# Generated by Django 3.0.4 on 2021-09-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='classes',
        ),
        migrations.AddField(
            model_name='classe',
            name='fornecedores',
            field=models.ManyToManyField(to='SimpleBuy.Fornecedor'),
        ),
        migrations.DeleteModel(
            name='ClasseFornecedor',
        ),
    ]
