# Generated by Django 3.0.4 on 2021-10-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0002_auto_20210911_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='plano',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
