# Generated by Django 3.0.4 on 2021-10-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0003_auto_20211003_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='icms',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='ipi',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='itens',
        ),
        migrations.RemoveField(
            model_name='ordemfornecimento',
            name='icms',
        ),
        migrations.RemoveField(
            model_name='ordemfornecimento',
            name='ipi',
        ),
        migrations.RemoveField(
            model_name='ordemfornecimento',
            name='itens',
        ),
        migrations.CreateModel(
            name='itens_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('quantidade', models.FloatField()),
                ('ipi', models.FloatField()),
                ('icms', models.FloatField()),
                ('cod_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Item')),
                ('num_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.OrdemFornecimento')),
            ],
        ),
        migrations.CreateModel(
            name='itens_nf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('quantidade', models.FloatField()),
                ('ipi', models.FloatField()),
                ('icms', models.FloatField()),
                ('cod_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Item')),
                ('num_nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.NotaFiscal')),
            ],
        ),
    ]
