# Generated by Django 3.0.4 on 2021-10-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0004_auto_20211009_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Classe'),
            preserve_default=False,
        ),
    ]
