# Generated by Django 3.0.4 on 2021-10-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0005_item_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_pendente_cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('data', models.DateTimeField()),
                ('cod_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Item')),
                ('solicitante_adm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Administrador')),
                ('solicitante_comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Comprador')),
            ],
        ),
    ]
