# Generated by Django 3.0.4 on 2021-10-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0006_item_pendente_cotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='fornecedores',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Classe'),
        ),
    ]
