# Generated by Django 3.0.4 on 2021-10-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0007_auto_20211012_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
