# Generated by Django 3.0.4 on 2021-10-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0008_auto_20211012_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
