# Generated by Django 3.0.4 on 2021-10-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0009_fornecedor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemfornecimento',
            name='dataEntrega',
        ),
        migrations.AddField(
            model_name='itens_of',
            name='dataEntrega',
            field=models.DateTimeField(null=True),
        ),
    ]
