# Generated by Django 3.0.4 on 2021-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0010_auto_20211012_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemfornecimento',
            name='frete',
        ),
        migrations.AddField(
            model_name='itens_of',
            name='frete',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
