# Generated by Django 3.0.4 on 2021-10-13 18:57

import SimpleBuy.enum.SituacaoOf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0011_auto_20211012_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemfornecimento',
            name='situacao',
            field=models.CharField(default=SimpleBuy.enum.SituacaoOf.SituacaoOf['COMPRADOR_NEGOCIANDO'], max_length=200),
        ),
    ]
