# Generated by Django 3.0.4 on 2021-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0013_auto_20211013_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_of',
            name='valor_unitario',
            field=models.FloatField(default=0),
        ),
    ]
