# Generated by Django 3.0.4 on 2021-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0014_itens_of_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='numeroNota',
            field=models.IntegerField(),
        ),
    ]
