# Generated by Django 3.0.4 on 2021-10-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0016_auto_20211016_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_nf',
            name='num_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.OrdemFornecimento'),
        ),
    ]
