# Generated by Django 3.0.4 on 2021-10-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0017_itens_nf_num_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_of',
            name='recebido',
            field=models.FloatField(default=0),
        ),
    ]
