# Generated by Django 3.0.4 on 2021-10-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0018_itens_of_recebido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresacompradora',
            name='cnpj',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='empresacompradora',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
