# Generated by Django 3.0.4 on 2021-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0020_auto_20211017_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemfornecimento',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
    ]
