# Generated by Django 3.0.4 on 2021-10-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0021_ordemfornecimento_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_of',
            name='solicitante_adm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Administrador'),
        ),
        migrations.AddField(
            model_name='itens_of',
            name='solicitante_comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Comprador'),
        ),
    ]
