from enum import Enum


class SituacaoOf(Enum):
    COMPRADOR_NEGOCIANDO = 'COMPRADOR_NEGOCIANDO'
    AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO'
    ABERTA = 'ABERTA'
    FECHADA = 'FECHADA'
    REPROVADA = 'REPROVADA'

